[package]
name = "bitnet"
version = "0.1.2"
authors = ["Shashwat Verma <me@shashwatverma.dev"]
repository = "https://github.com/Imyr/BitNet/"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.1.4", features = ["derive"] }
reqwest = "0.11.13"
